name: Auto Commit

on:
  schedule:
    - cron: '0 0 * * *' # Menjadwalkan tugas setiap hari pada tengah malam

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Remove previous update line
        shell: bash
        run: |
          if grep -q '^Last update:' README.md; then
            sed -i '/^Last update:/d' README.md
          fi

      - name: Ensure README file exists
        run: touch README.md

      - name: Update README file
        run: echo "Last update: $(date -u '+%Y-%m-%d %H:%M:%S %Z')" >> README.md

      - name: Check for changes
        shell: bash
        run: |
          if git diff --quiet; then
            echo "No changes to commit."
            exit 0
          fi

      - name: Configure Git
        run: |
          git config --global user.name 'TarnaWijaya'
          git config --global user.email 'tarnaindramayuu@gmail.com'

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add README.md
          git commit -m "Automated commit by GitHub Actions on $(date -u '+%Y-%m-%d %H:%M:%S %Z')"
          git push origin HEAD:main